apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificates.yaml
  - repository.yaml
  - repository-smi.yaml
  - release-crds.yaml
  - release-control-plane.yaml
  - release-smi.yaml
