apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: develop
resources:
  - ../../base
  - namespace.yaml
  - image-policy.yaml
  - image-automation.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: ghcr.io/ldbl/frontend
    newTag: develop-v0.0.2-96e77b8-1771607403 # {"$imagepolicy": "develop:frontend:tag"}
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
