---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base
  - namespace.yaml
  - image-policy.yaml
  - image-automation.yaml
images:
  - name: ghcr.io/ldbl/frontend
    newTag: production-v0.0.0-0000000-0000000000 # {"$imagepolicy": "production:frontend:tag"}
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
