---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: backend
  namespace: staging
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Update staging backend image

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Changed.Images -}}
        - {{.}} ({{.Policy.Name}})
        {{ end -}}

        [ci skip]
    push:
      branch: main
  update:
    path: ./flux/apps/backend/staging
    strategy: Setters
