---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: backend
  namespace: staging
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-image-automation
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Update staging backend image

        [ci skip]
    push:
      branch: main
  update:
    path: ./flux/apps/backend/staging
    strategy: Setters
