apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - namespace.yaml
  - image-policy.yaml
  - image-automation.yaml
images:
  - name: ghcr.io/ldbl/frontend
    newTag: staging-v0.0.0-f025044-1770308200 # {"$imagepolicy": "staging:frontend:tag"}
    digest: "" # {"$imagepolicy": "staging:frontend:digest"}
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
