apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - namespace.yaml
  - image-policy.yaml
  - image-automation.yaml
images:
  - name: ghcr.io/ldbl/frontend
    newTag: staging-v0.0.2-857701d-1770396165 # {"$imagepolicy": "staging:frontend:tag"}
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
