apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository-cert-manager.yaml
  - repository-external-dns.yaml
  - release-cert-manager.yaml
  - release-external-dns.yaml
  - cluster-issuer.yaml
