apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - test-namespace.yaml
# Add more kustomizations here as you create them
# - apps.yaml
# - infrastructure.yaml
